### ISSUE TITLE
 problem on start of ubuntu binaries

### ISSUE THREAD

**Issue by smatiush** [absolute-community/absolute-archive#34]
`"error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory"`
this is the error that print out the terminal when i try to execute the wallet.
the binaries needs dependencies?

**Comment by Billi7676** [comment]
binaries are compiled on ubuntu 16.04... so you need this os on vps
also you need to intall some deps too (i took them from an install script):
apt-get install nano git pwgen python virtualenv python-virtualenv software-properties-common libzmq5 libboost-system1.58.0 libboost-filesystem1.58.0 libboost-program-options1.58.0 libboost-thread1.58.0 libboost-chrono1.58.0 libevent-pthreads-2.0-5 libminiupnpc10 libevent-2.0-5 -y -qq
add-apt-repository ppa:bitcoin/bitcoin -y
apt-get update -y -qq
apt-get upgrade -y -qq
apt-get install libdb4.8-dev libdb4.8++-dev -y -qq

**Comment by CryptoCentric** [comment]
Fixed in v12.2.5
